AttributeError when issue.status is None
When there is no status assigned, issue.status is None. That throws an AttributeError: 'NoneType' object has no attribute 'text'